#!/bin/bash

# Note: 
# This script is sourced by the its wrapper script. 
# Do not execute this directly!

selfupdate-help() {
    echo "Run selfupdate --nosync in the MacPorts installation specified by the --prefix flag"
}

selfupdate() {
    if [ ! -f "${option_prefix}/bin/port" ]; then
        macports_version=2.3.4
        macports_distname=MacPorts-${macports_version}
        macports_distfile=${macports_distname}.tar.bz2
        if [ ! -d ${macports_distname} ]; then
            if [ ! -f ${macports_distfile} ]; then
                curl -fIsLO https://distfiles.macports.org/MacPorts/${macports_distfile} || return $?
            fi
            tar -xJf ${macports_distfile} || return $?
        fi
        cd ${macports_distname} || return $?
        ./configure --prefix=${option_prefix} --enable-readline || return $?
        make -j$(sysctl -n hw.activecpu) || return $?
        make install || return $?
        cd .. || return $?
        rm -rf ${macports_distfile} ${macports_distname} || return $?
    fi

    "${option_prefix}/bin/port" -d selfupdate --nosync || return $?
}
