#!/bin/bash
# -*- coding: utf-8; mode: sh; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- vim:fenc=utf-8:ft=sh:et:sw=4:ts=4:sts=4

# Note:
# This script is sourced by the mpbb wrapper script.
# Do not execute this directly!

checkout-usage() {
    # "prog" is defined in mpbb-help.
    # shellcheck disable=SC2154
    cat <<EOF
usage: $prog [<global opts>] checkout [<opts>]

Obtain a working copy of the jobs tools and ports tree and configure
MacPorts to use the latter as a port source.

Options:

  --jobs-url=<URL>
    URL to a repository containing the jobs tools. Only used when
    checking out a new working copy. Defaults to
    \`https://svn.macports.org/repository/macports/trunk/base/portmgr/jobs'.

  --ports-commit=<commit>
    A commit or revision at which the ports tree will be checked out.
    Any specifier understood by the version-control client may be used.
    Defaults to \`HEAD'.

  --ports-url=<URL>
    URL to a repository containing the ports tree. Only used when
    checking out a new working copy. Defaults to
    \`https://svn.macports.org/repository/macports/trunk/dports'.

  --svn[=<path>]
    Use Subversion to obtain the jobs tools and ports tree; this is the
    default behavior. The path to a Subversion client may be provided
    explicitly, otherwise \`svn' is used.

Run \`$prog help' for global options and a list of other subcommands.
EOF
}

checkout() {
    local args
    parseopt jobs-url:,ports-commit:,ports-url:,prefix:,svn::,svn-url: "$@" \
        || return
    # shellcheck disable=SC2086
    set -- ${args+"${args[@]}"}

    # shellcheck disable=SC2154
    # To maintain backwards compatibility, --svn-url implies --svn.
    if [[ -n ${option_svn_url+_} ]]; then
        : "${option_svn=}"
    fi

    # shellcheck disable=SC2154
    local -r ports_dir=${option_work_dir}/dports

    local jobs_dir svn
    # shellcheck disable=SC2154
    if svn=${option_svn:-$(command -v svn)}; then
        jobs_dir=${option_work_dir}/tools
        if [[ -n ${option_svn_url+_} ]]; then
            : "${option_jobs_url=${option_svn_url}/base/portmgr/jobs}"
            : "${option_ports_url=${option_svn_url}/dports}"
        else
            : "${option_jobs_url=https://svn.macports.org/repository/macports/trunk/base/portmgr/jobs}"
            : "${option_ports_url=https://svn.macports.org/repository/macports/trunk/dports}"
        fi
    if [[ -d "${jobs_dir}/.svn" ]] ; then
        echo "Update macports tools from svn..."
        if [[ -e "${jobs_dir}/.svn/lock" ]]; then
            "$svn" --non-interactive cleanup "${jobs_dir}" || return
        fi
        "$svn" update --non-interactive \
            -r HEAD \
            "${jobs_dir}" || return
    else
        echo "Checking out macports tools from svn..."
        mkdir -p "$(dirname "${jobs_dir}")"
        "$svn" checkout --non-interactive \
            -r HEAD "${option_jobs_url}" \
            "${jobs_dir}" || return
    fi

    if [[ -d "${ports_dir}/.svn" ]] ; then
        echo "Update macports from svn..."
        # TODO: add switching of SVN server
        if [[ -e "${ports_dir}/.svn/lock" ]]; then
            "$svn" --non-interactive cleanup "${ports_dir}" || return
        fi
        "$svn" update --non-interactive \
            -r "${option_ports_commit-HEAD}" \
            "${ports_dir}" || return
    else
        echo "Checking out macports from svn..."
        mkdir -p "$(dirname "${ports_dir}")"
        "$svn" checkout --non-interactive \
            -r "${option_ports_commit-HEAD}" "${option_ports_url}" \
            "${ports_dir}" || return
    fi
    else
        err 'cannot find a Subversion client'
        return 1
    fi

    # $option_prefix is set in mpbb
    # shellcheck disable=SC2154
    (cd "${ports_dir}" && "${option_prefix}/bin/portindex") || return

    local -ar mirrors=(aarnet.au cjj.kr fco.it her.gr jnb.za jog.id
                       lil.fr mse.uk nou.nc nue.de osl.no sea.us ykf.ca)
    # Unset IFS to ensure "${mirrors[*]}" uses spaces as separators.
    (unset IFS && cat > "${option_work_dir}/macports.conf" <<EOF
# Automatically overwritten by mpbb-checkout
# Do not edit !!!
sources_conf ${option_work_dir}/sources.conf
host_blacklist ${mirrors[*]/%/.distfiles.macports.org} \
               ${mirrors[*]/%/.packages.macports.org}
EOF
) || return

    cat > "${option_work_dir}/sources.conf" <<EOF || return
# Automatically overwritten by mpbb-checkout
# Do not edit !!!
file://${ports_dir} [default]
EOF

}
