#!/bin/bash

# Note:
# This script is sourced by the mpbb wrapper script.
# Do not execute this directly!


install-dependencies-help() {
    echo "Build and install all dependencies of port --port."
}

install-dependencies() {
    if [ -z "${option_port}" ]; then
        errmsg "--port is required"
        return 1
    fi

    # skip if the port has no dependencies
    if [ -z "$(${option_prefix}/bin/port echo depof:${option_port})" ]; then
        return 0
    fi

    if ! "${option_prefix}/bin/port" -d install --unrequested depof:"${option_port}"; then
        echo "Build failed, cleaning up..."
        cleanup
        return 1
    fi
}
