#!/bin/bash

# Note:
# This script is sourced by the mpbb wrapper script.
# Do not execute this directly!

cleanup-help() {
    echo "Clean up build remnants and leftovers caused by the build of port --port and its dependencies."
}

cleanup() {
    if [ -z "${option_port}" ]; then
        errmsg "--port is required"
        return 1
    fi

    echo "Running cleanup..."
    # Deactivate all ports
    "${option_prefix}/bin/port" -fp deactivate active
    # Clean the ports we built and their dependencies
    "${option_prefix}/bin/port" -fp clean --dist --logs --work "${option_port}" rdepof:"${option_port}"
    # Uninstall obsolete ports
    "${option_prefix}/bin/port-tclsh" "${thisdir}/tools/uninstall-old-ports.tcl"
}
