#!/bin/bash

# Note:
# This script is sourced by the mpbb wrapper script.
# Do not execute this directly!


subports-help() {
    echo "Determine subports for the port given by the --port option."
}

subports() {
    if [ -z "${option_port}" ]; then
        errmsg "--port is required"
        return 1
    fi

    status=0
    PREFIX=${option_prefix} $thisdir/tools/subports.tcl "${option_port}" || status=$?

    return $status
}
