#!/bin/bash

# Note:
# This script is sourced by the mpbb wrapper script.
# Do not execute this directly!


gather-archives-help() {
    echo "Gather unpublished distributable archives of the built port and its dependencies."
}

gather-archives() {
    curl=/usr/bin/curl
    tclsh=${option_prefix}/bin/port-tclsh

    if [ -d "${option_staging_dir}" ]; then
        find "${option_staging_dir}" -type f -delete -print | sed -E -e "s|^.*/||" -e 's/^/Deleting previously staged archive: /'
        rm -rf "${option_staging_dir}"
        echo
    fi

    mkdir -p "${option_staging_dir}" || return $?

    status=0
    for archive_path in $("${option_prefix}/bin/port" -q location active); do
        archive_port=$(basename "$(dirname "${archive_path}")")
        archive_basename=$(basename "${archive_path}")

        if ! ${curl} -fIsL "${option_archive_site}/${archive_port}/${archive_basename}" > /dev/null; then
            if "${tclsh}" "${option_workdir}/tools/port_binary_distributable.tcl" -v "${archive_port}"; then
                echo "Staging archive for upload: ${archive_basename}"
                mkdir -p "${option_staging_dir}/${archive_port}" || { status=$?; break; }
                ln "${archive_path}" "${option_staging_dir}/${archive_port}/${archive_basename}" || { status=$?; break; }
            fi
        fi
    done
    
    cleanup
    return $status
}
