#!/bin/sh
#
# This is run in the chroot, so don't run yourself...
#
# Copyright (c) 2006,2008 Bryan L Blackburn.  All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in
#    the documentation and/or other materials provided with the
#    distribution.
# 3. Neither the name Bryan L Blackburn, nor the names of any contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS ``AS IS''
# AND ANY EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

if [[ -z "$PREFIX" ]]; then
    PREFIX=/opt/local
fi
ARCHIVE_TYPE=".tbz2"

function uninstallPorts()
{
   installedPorts=`${PREFIX}/bin/port echo active | /usr/bin/awk '{print $1}'`
   for uninstallPort in $installedPorts; do
      echo "Deactivating $uninstallPort"
      portOutput=`${PREFIX}/bin/port -dvf deactivate $uninstallPort 2>&1`
      if [[ $? != 0 ]]; then
         echo $portOutput
         break
      fi
   done
}


function cleanBuildStuff()
{
   rm -rf ${PREFIX}/var/macports/build/*
   uninstallPorts
   if [[ $? != 0 ]]; then
      echo "Uninstall failed, aborting"
      exit 1
   fi
}


cleanBuildStuff
PORTRESULTSDIR="/var/tmp/portresults"
PROGRESSLOG="/var/tmp/progress.log"
FAILCACHE="/var/tmp/failcache"
rm -rf ${PORTRESULTSDIR}
/bin/mkdir -p ${PORTRESULTSDIR}/success ${PORTRESULTSDIR}/fail

useFailCache=""
if [[ -f /var/tmp/portlist && `head -n1 /var/tmp/portlist` != "all" ]]; then
   portList=`/bin/cat /var/tmp/portlist`
else
   portList=`/usr/bin/tclsh /var/tmp/genportlist.tcl`
   useFailCache=1
fi
/bin/rm -f /var/tmp/portlist

portCount=`echo ${portList} | /usr/bin/wc -w`
portCount=$(($portCount))   # Get rid of wc's spacing

tclOS=`echo 'puts [string tolower $tcl_platform(os)]' | tclsh`
tclOSMajor=`echo 'puts [lindex [split $tcl_platform(osVersion) .] 0]' | tclsh`
packageDir="${PREFIX}/var/macports/software"
shopt -s extglob
if [[ $tclOSMajor -ge 10 ]]; then
    ACCEPT_ARCHS="+(noarch|x86_64|i386|-)"
else
    ACCEPT_ARCHS="+(noarch|i386|ppc|-)"
fi

currentCount=1
for portName in ${portList}; do
   trap "echo \"Canceled, cleaning up...\"; cleanBuildStuff" EXIT

   echo "Building ${portName} (${currentCount} of ${portCount})...\c" | tee -a ${PROGRESSLOG}
   # If there's a package, don't build again
   portVersion=`${PREFIX}/bin/port info --index --version --line ${portName}`
   portRevision=`${PREFIX}/bin/port info --index --revision --line ${portName}`
   portPackageBaseName="${portName}-${portVersion}_${portRevision}"
   ls ${packageDir}/${portName}/${portPackageBaseName}[+.]*${tclOS}_${tclOSMajor}.${ACCEPT_ARCHS}${ARCHIVE_TYPE} > /dev/null 2>&1
   if [[ $? == 0 ]]; then
      echo "package found, not building again" | tee -a ${PROGRESSLOG} | tee ${PORTRESULTSDIR}/success/${portName}.log
   else
      skipPort=""
      portFile=`${PREFIX}/bin/port file ${portName}`
      if [[ -n "$useFailCache" && ! "$portFile" -nt "${FAILCACHE}/${portName}" ]]; then
         echo "skipping, portfile not modified since last failure" | tee -a ${PROGRESSLOG} | tee ${PORTRESULTSDIR}/fail/${portName}.log
         skipPort=1
      else
         portDeps=`${PREFIX}/bin/port info --index --depends --line ${portName} | /usr/bin/tr ',' ' '`
         nonPortDeps=""
         for oneDep in ${portDeps}; do
            depType=`echo ${oneDep} | /usr/bin/awk -F : '{print $1}'`
            if [[ $depType == "port" ]]; then
               depName=`echo ${oneDep} | /usr/bin/awk -F : '{print $2}'`
               if [[ -f ${PORTRESULTSDIR}/fail/${depName}.log ]]; then
                  skipPort=1
                  echo "skipping, $depName previously failed and is needed" | tee -a ${PROGRESSLOG}
                  echo "${portName} not built due to failed dependency $depName" > ${PORTRESULTSDIR}/fail/${portName}.log
                  break
               fi
            else
               nonPortDeps=1
            fi
         done
      fi
      if [[ -z "$skipPort" ]]; then
         ${PREFIX}/bin/port -dv install $portName | tee ${PORTRESULTSDIR}/${portName}.log 2>&1
         if [[ ${PIPESTATUS[0]} == 0 ]]; then
            /bin/mv ${PORTRESULTSDIR}/${portName}.log ${PORTRESULTSDIR}/success
            echo "success" | tee -a ${PROGRESSLOG}
            rm -f ${FAILCACHE}/${portName}
         else
            /bin/mv ${PORTRESULTSDIR}/${portName}.log ${PORTRESULTSDIR}/fail
            echo "failure" | tee -a ${PROGRESSLOG}
            ${PREFIX}/bin/port clean --work $portName
            # check that it definitely failed in its own right before caching
            if [[ -z "$nonPortDeps" ]]; then
               touch -r ${portFile} ${FAILCACHE}/${portName}
            fi
         fi
         uninstallPorts
         if [[ $? != 0 ]]; then
            echo "Uninstall failed, aborting"
            exit 2
         fi
      fi
   fi
   currentCount=$((${currentCount}+1))
done

trap "" EXIT

cleanBuildStuff

exit 0

